const userResults = [
  {
    name: "Daily life",
    subtitle: "Daily rhythms and life management",
    alignmentPercentage: 40,
    icon: "/daily-organization.png",
    alignmentText: "You both value organization but bring different strengths to your daily routine.",
    growthOpportunity: "Find balance between structure and flexibility in weekend plans.",
  },
  {
    name: "Communication",
    subtitle: "Connection patterns and emotional expression",
    alignmentPercentage: 50,
    icon: "/communication-style.png",
    alignmentText: "You align well in expressing emotions but differ in resolving conflicts.",
    growthOpportunity: "Explore more constructive ways to handle conflicts together.",
  },
  {
    name: "Intimacy",
    subtitle: "Emotional and physical connection patterns",
    alignmentPercentage: 60,
    icon: "/compatibility.png",
    alignmentText: "Your emotional connection is strong but could benefit from more physical time together.",
    growthOpportunity: "Plan dedicated moments for deeper connection.",
  },
  {
    name: "Growth",
    subtitle: "Handling transitions and development",
    alignmentPercentage: 70,
    icon: "/growth.png",
    alignmentText: "You handle transitions well together but struggle with differing priorities.",
    growthOpportunity: "Align priorities during major transitions.",
  },
  {
    name: "Social life",
    subtitle: "Managing relationships and boundaries",
    alignmentPercentage: 50,
    icon: "/social-life.png",
    alignmentText: "Your boundaries align well but can differ during group activities.",
    growthOpportunity: "Explore common interests in social settings.",
  },
  {
    name: "Future goals",
    subtitle: "Vision alignment and life direction",
    alignmentPercentage: 64,
    icon: "/future-goals.png",
    alignmentText: "Your long-term goals align but need regular reassessment.",
    growthOpportunity: "Set periodic check-ins to review life direction.",
  },
  {
    name: "Parenting values",
    subtitle: "Child-rearing philosophy and approaches",
    alignmentPercentage: 40,
    icon: "/parenting-values.png",
    alignmentText: "You both value consistency but bring different strengths to parenting You both value consistency but bring different strengths to parenting. You both value consistency but bring different strengths to parenting. You both value consistency but bring different strengths to parenting. You both value consistency but bring different strengths to parenting..",
    growthOpportunity: "Discuss and align parenting strategies during milestones.",
  },
  {
    name: "Finances",
    subtitle: "Money management and financial values",
    alignmentPercentage: 55,
    icon: "/finances.png",
    alignmentText: "You approach budgeting differently but share similar financial goals.",
    growthOpportunity: "Create a shared financial plan to optimize spending.",
  },
];

export default userResults;