import "./globals.css";
import Provider from "@/app/Provider";
import { modernEra } from "@/fonts/typo";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${modernEra.className}  antialiased`}
      >
        <Provider>
            {children}
        </Provider>
      </body>
    </html>
  );
}
